import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import CommandMenu from "@/components/CommandMenu";
import Sidebar from "@/components/Sidebar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-screen overflow-hidden">
        <Sidebar />
        <CommandMenu />
        <main className="ml-64 h-screen overflow-y-auto p-5 lg:ml-[20%] lg:p-8">
          <div className="mx-auto w-full max-w-7xl">{children}</div>
        </main>
      </body>
    </html>
  );
}
